name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Cache dependencies
        id: cache-lint
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.lint.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.lint.txt
      - name: Run linters
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Cache dependencies
        id: cache-test
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.test.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt -r requirements/requirements.test.txt
      - name: Run tests
        run: |
          export PYTHONUNBUFFERED=1
          export NMC_DEBUG=1
          export NMC_USE_STUBS=1
          export NMC_TESTING=1
          export NMC_CI=1
          export PYTEST_ADDOPTS="--ignore-glob=tests/functional/*"
          make test
